extends:
  - 'airbnb-base'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'prettier'

plugins:
  - '@typescript-eslint'

parser: '@typescript-eslint/parser'

parserOptions:
  sourceType: 'module'
  project: './tsconfig.json'

env:
  browser: true
  node: true
  es2021: true
# rules:
# 個別に設定するESLintルールを記述
